version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: e_commerce
    ports:
      - "5432:5432" # PostgreSQL default port

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/e_commerce
    ports:
      - "8000:8000"

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: game-of-three-app
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/game_of_three
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_JPA_SHOW_SQL: "true"
#    depends_on:
#      - postgres
#    ports:
#      - "8091:8091"